/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayintarlasi;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author Zafer
 */
public final class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
       initComponents();
     
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OyunjMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        NewjMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        BeginnerjCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        IntermediatejCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        ExpertjCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        CustomjCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ExitjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(374, 300));

        jLabel1.setText("Lütfen game kısmından oyun düzeyini seçiniz. ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        OyunjMenu.setText("Game");
        OyunjMenu.add(jSeparator1);

        NewjMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        NewjMenuItem.setText("New");
        NewjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewjMenuItemActionPerformed(evt);
            }
        });
        OyunjMenu.add(NewjMenuItem);
        OyunjMenu.add(jSeparator2);

        BeginnerjCheckBoxMenuItem.setText("Beginner");
        BeginnerjCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginnerjCheckBoxMenuItemActionPerformed(evt);
            }
        });
        OyunjMenu.add(BeginnerjCheckBoxMenuItem);

        IntermediatejCheckBoxMenuItem.setText("Intermediate");
        IntermediatejCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntermediatejCheckBoxMenuItemActionPerformed(evt);
            }
        });
        OyunjMenu.add(IntermediatejCheckBoxMenuItem);

        ExpertjCheckBoxMenuItem.setText("Expert");
        ExpertjCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertjCheckBoxMenuItemActionPerformed(evt);
            }
        });
        OyunjMenu.add(ExpertjCheckBoxMenuItem);

        CustomjCheckBoxMenuItem.setText("Custom");
        CustomjCheckBoxMenuItem.setEnabled(false);
        OyunjMenu.add(CustomjCheckBoxMenuItem);
        OyunjMenu.add(jSeparator3);

        ExitjMenuItem.setText("Exit");
        ExitjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjMenuItemActionPerformed(evt);
            }
        });
        OyunjMenu.add(ExitjMenuItem);

        jMenuBar1.add(OyunjMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewjMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AnaEkran a=new AnaEkran();
        a.setVisible(true);
    }//GEN-LAST:event_NewjMenuItemActionPerformed

    private void ExitjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjMenuItemActionPerformed
        // TODO add your handling code here:
       int cevap= JOptionPane.showConfirmDialog(null,"Çıkmak istediğinizden eminmisiniz?","Bilgi",JOptionPane.YES_NO_OPTION);
               if (cevap == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitjMenuItemActionPerformed

    private void IntermediatejCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntermediatejCheckBoxMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AnaEkran a= new AnaEkran();
        a.Oyunduzeyi(2);
        a.gecenzaman();
        a.IntermediatejCheckBoxMenuItem.setState(true);
        a.BeginnerjCheckBoxMenuItem.setState(false);
        a.ExpertjCheckBoxMenuItem.setState(false);
        a.CustomjCheckBoxMenuItem.setState(false);
        a.setVisible(true);
    }//GEN-LAST:event_IntermediatejCheckBoxMenuItemActionPerformed

    private void BeginnerjCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginnerjCheckBoxMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AnaEkran a= new AnaEkran();
        a.Oyunduzeyi(1);
        a.gecenzaman();
        a.BeginnerjCheckBoxMenuItem.setState(true);
        a.IntermediatejCheckBoxMenuItem.setState(false);
        a.ExpertjCheckBoxMenuItem.setState(false);
        a.CustomjCheckBoxMenuItem.setState(false);
        a.setVisible(true);
        
    }//GEN-LAST:event_BeginnerjCheckBoxMenuItemActionPerformed

    private void ExpertjCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertjCheckBoxMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AnaEkran a= new AnaEkran();
        a.Oyunduzeyi(3);
        a.gecenzaman();
        a.ExpertjCheckBoxMenuItem.setState(true);
        a.IntermediatejCheckBoxMenuItem.setState(false);
        a.BeginnerjCheckBoxMenuItem.setState(false);
        a.CustomjCheckBoxMenuItem.setState(false);
        a.setVisible(true);
        
    }//GEN-LAST:event_ExpertjCheckBoxMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
 int sayac=0;  
 byte ToplamBombaSayisi,a,b;
 ArrayList<JButton> dizi = new ArrayList<>();
 ArrayList<Integer> dizidurum = new ArrayList<>();
 public JTextField GecenZamantf; 
 public JTextField BombaSayisitf;
 
 public void Oyunduzeyi(int düzey)
 {
     jLabel1.setVisible(false);
     if (düzey==1) {
              a=9;b=9;
      ButtonOlustur();
     }
      if (düzey==2) {
              a=16;b=16;
      ButtonOlustur();
     }
       if (düzey==3) {
              a=16;b=30;
      ButtonOlustur();
     }
       if (düzey==4) {
           if (b==9) {
            a=9;b=9;
           ButtonOlustur();
            }
          else if (b==16) {
             a=16;b=16;
            ButtonOlustur();
           }
          else if (b==30) {
               a=16;b=30;
            ButtonOlustur();
           }
       }
       
//     
 }
 private void gecenzaman() {
      Timer zamanliyici=new Timer();
     TimerTask gorev=new TimerTask()
     {
     @Override
        public void run(){
            sayac++;
            GecenZamantf.setText(Integer.toString(sayac));
        }
     };
     zamanliyici.schedule(gorev,0,1000);
    }
 //a lar b olarak düzeltilecek
 private class Listener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
        JButton GelenButton=(JButton)e.getSource();
        byte bombasayisi=0;
            if (dizidurum.get(Integer.parseInt(GelenButton.getName()))==0 ) {
                for (int i = 0; i < 2*b+1; i+=b) {
                    //sol kısım başladı
                    if (Integer.parseInt(GelenButton.getName())%b==0) {
                        if (Integer.parseInt(GelenButton.getName())==0) {
                             if ( dizidurum.get(1)==1) 
                            {
                                bombasayisi+=1;
                            }  
                            if ( dizidurum.get(b)==1) 
                            {
                                bombasayisi+=1;
                            }
                              if ( dizidurum.get(b+1)==1) 
                            {
                               bombasayisi+=1;
                            }
                              break;
                        }
                        else if (Integer.parseInt(GelenButton.getName())==b*(a-1)) {
                             if ( dizidurum.get(b*(a-1)-b)==1) 
                            {
                                bombasayisi+=1;
                            }  
                          else  if ( dizidurum.get(b*(a-1)-(b-1))==1) 
                            {
                                bombasayisi+=1;
                            }
                          else if ( dizidurum.get(b*(a-1)+1)==1) 
                            {
                               bombasayisi+=1;
                            }
                              break;
                        }
                        else{                    
                            if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+i)==1) 
                            {
                                bombasayisi+=1;
                            }
                              if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+1+i)==1) 
                            {
                               bombasayisi+=1;
                            }
                        }
                         
                    }
                    //sol kısım bitti sağ kısım başladı
                      else if (Integer.parseInt(GelenButton.getName())%b==b-1) {
                                if (Integer.parseInt(GelenButton.getName())==b-1) {
                             if ( dizidurum.get(b-2)==1) 
                            {
                                bombasayisi+=1;
                            }  
                            if ( dizidurum.get((b-1)*2)==1) 
                            {
                                bombasayisi+=1;
                            }
                              if ( dizidurum.get((b-1)*2+1)==1) 
                            {
                               bombasayisi+=1;
                            }
                              break;
                        }
                        else if (Integer.parseInt(GelenButton.getName())==a*b-1) {
                             if ( dizidurum.get(a*b-(b-1))==1) 
                            {
                                bombasayisi+=1;
                            }  
                            if ( dizidurum.get(a*b-b)==1) 
                            {
                                bombasayisi+=1;
                            }
                              if ( dizidurum.get(a*b-2)==1) 
                            {
                               bombasayisi+=1;
                            }
                              break;
                        }
                        else{     
                             if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b-1+i)==1) 
                            {
                                bombasayisi+=1;
                            }  
                            if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+i)==1) 
                            {
                                bombasayisi+=1;
                            }
                            
                        }
                    }//sağ kısım bitti üst kısım başladı
                       else if (Integer.parseInt(GelenButton.getName())<b-1) {
                           if (i<=b) {
                              if ( dizidurum.get(Integer.parseInt(GelenButton.getName())+i-1)==1) 
                            {
                                bombasayisi+=1;
                            }  
                            if ( dizidurum.get(Integer.parseInt(GelenButton.getName())+i)==1) 
                            {
                                bombasayisi+=1;
                            }
                              if ( dizidurum.get(Integer.parseInt(GelenButton.getName())+i+1)==1) 
                            {
                               bombasayisi+=1;
                            }
                              }
                              else{break;}
                    }
                    //üst kısım bitti alt kısım başladı 
                       else if (Integer.parseInt(GelenButton.getName())>=b*(a-1)-1) {
                            if (i<=b) {
                              if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b-1+i)==1) 
                                {
                                    bombasayisi+=1;
                                }  
                                if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+i)==1) 
                                {
                                    bombasayisi+=1;
                                }
                                  if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+1+i)==1) 
                                {
                                   bombasayisi+=1;
                                }
                            }
                             else{break;}
                    }
                       else {
                           if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b-1+i)==1) 
                            {
                                bombasayisi+=1;
                            }  
                            if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+i)==1) 
                            {
                                bombasayisi+=1;
                            }
                              if ( dizidurum.get(Integer.parseInt(GelenButton.getName())-b+1+i)==1) 
                            {
                               bombasayisi+=1;
                            }
                       }    
               }
              GelenButton.setText(Integer.toString(bombasayisi));
            }
            else{
                JOptionPane.showMessageDialog(null,"Game Over");
                GelenButton.setText("b");
            }
            GelenButton.setEnabled(false);
        }
    }

  private class Yenidenbaslat implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            AnaEkran a= new AnaEkran();
              a.b=b;
             a.Oyunduzeyi(4);
            a.gecenzaman();
            a.setVisible(true);
             AnaEkran.this.setVisible(false);
          
           }
         
  }
    public void ButtonOlustur()
    {   
        if (a==9 && b==9) {
           this.setSize(460, 540); //formu boyutlandır
                BombaSayisitf = new JTextField("BombaSayisitf");//butonu oluştur
                BombaSayisitf.setFont(new Font("Terminal",Font.CENTER_BASELINE,24));
                BombaSayisitf.setBounds(8,13,50, 35);
                BombaSayisitf.setEnabled(false);
                BombaSayisitf.setDisabledTextColor(new Color(204,0,0));
                BombaSayisitf.setBackground(new Color(102,102,102));
                BombaSayisitf.setForeground(new Color(204,0,0)); 
                BombaSayisitf.setHorizontalAlignment(SwingConstants.CENTER);
                BombaSayisitf.setName("BombaSayisitf");
                BombaSayisitf.setText("");
                Border kaplama2=BorderFactory.createLoweredSoftBevelBorder();
                BombaSayisitf.setBorder(kaplama2);
                this.add(BombaSayisitf);
           
                GecenZamantf = new JTextField("GecenZamantf");//butonu oluşturnew 
                GecenZamantf.setFont(new Font("Terminal",Font.CENTER_BASELINE,24));
                GecenZamantf.setBounds(385,13,50, 35);
                GecenZamantf.setEnabled(false);
                GecenZamantf.setDisabledTextColor(new Color(204,0,0));
                GecenZamantf.setBackground(new Color(102,102,102));
                GecenZamantf.setForeground(new Color(204,0,0)); 
                GecenZamantf.setHorizontalAlignment(SwingConstants.CENTER);
                GecenZamantf.setName("GecenZamantf");
                GecenZamantf.setBorder(kaplama2);
                GecenZamantf.setText("");
                 this.add(GecenZamantf);
           
           final JButton YenidenBaslatbt = new JButton("YenidenBaslatbt");//butonu oluştur
               YenidenBaslatbt.setFont(new Font("Tahoma", Font.PLAIN, 9));
                YenidenBaslatbt.setBounds(158,12,124, 35);
                YenidenBaslatbt.setBackground(Color.green);
                YenidenBaslatbt.setForeground(Color.black); 
                YenidenBaslatbt.setName("YenidenBaslatbt");
                YenidenBaslatbt.setText("Yeniden Başlat");
                YenidenBaslatbt.addActionListener(new Yenidenbaslat());
                 this.add(YenidenBaslatbt);
            final JPanel Jpanel2 = new JPanel();//paneli oluştur
               Jpanel2.setFont(new Font("Tahoma", Font.PLAIN, 9));
                Jpanel2.setBounds(0,10, 440, 40);
                Jpanel2.setBackground(Color.lightGray);
                Jpanel2.setName("YenidenBaslatbt");
                Border kaplama=BorderFactory.createLoweredBevelBorder();
                Jpanel2.setBorder(kaplama);
                 this.add(Jpanel2);
        }
            /*---------------------------16-16-----------------------------*/
            if (a==16 && b==16) {
           this.setSize(745, 800); //formu boyutlandır
                BombaSayisitf = new JTextField("BombaSayisitf");//butonu oluştur
                BombaSayisitf.setFont(new Font("Terminal",Font.CENTER_BASELINE,24));
                BombaSayisitf.setBounds(8,17,70, 45);
                BombaSayisitf.setEnabled(false);
                BombaSayisitf.setDisabledTextColor(new Color(204,0,0));
                BombaSayisitf.setBackground(new Color(102,102,102));
                BombaSayisitf.setForeground(new Color(204,0,0)); 
                BombaSayisitf.setName("BombaSayisitf");
                BombaSayisitf.setText("");
                BombaSayisitf.setHorizontalAlignment(SwingConstants.CENTER);
                Border kaplama2=BorderFactory.createLoweredSoftBevelBorder();
                BombaSayisitf.setBorder(kaplama2);
                this.add(BombaSayisitf);
           
                GecenZamantf = new JTextField("GecenZamantf");//butonu oluşturnew 
                GecenZamantf.setFont(new Font("Terminal",Font.CENTER_BASELINE,24));
                GecenZamantf.setBounds(650,17,70, 45);
                GecenZamantf.setEnabled(false);
                GecenZamantf.setDisabledTextColor(new Color(204,0,0));
                GecenZamantf.setBackground(new Color(102,102,102));
                GecenZamantf.setForeground(new Color(204,0,0)); 
                GecenZamantf.setHorizontalAlignment(SwingConstants.CENTER);
                GecenZamantf.setName("GecenZamantf");
                GecenZamantf.setBorder(kaplama2);
                GecenZamantf.setText("");
                 this.add(GecenZamantf);
           
           final JButton YenidenBaslatbt = new JButton("YenidenBaslatbt");//butonu oluştur
               YenidenBaslatbt.setFont(new Font("Tahoma", Font.PLAIN, 9));
                YenidenBaslatbt.setBounds(308,18,124, 45);
                YenidenBaslatbt.setBackground(Color.green);
                YenidenBaslatbt.setForeground(Color.black); 
                YenidenBaslatbt.setName("YenidenBaslatbt");
                YenidenBaslatbt.setText("Yeniden Başlat");
                YenidenBaslatbt.addActionListener(new Yenidenbaslat());
                 this.add(YenidenBaslatbt);
            final JPanel Jpanel2 = new JPanel();//paneli oluştur
               Jpanel2.setFont(new Font("Tahoma", Font.PLAIN, 9));
                Jpanel2.setBounds(0,10, 735, 60);
                Jpanel2.setBackground(Color.lightGray);
                Jpanel2.setName("YenidenBaslatbt");
                Border kaplama=BorderFactory.createLoweredBevelBorder();
                Jpanel2.setBorder(kaplama);
                 this.add(Jpanel2);
        }
            /*---------------------------16-30-----------------------------*/
                if (a==16 && b==30) {
           this.setSize(1302, 800); //formu boyutlandır
                BombaSayisitf = new JTextField("BombaSayisitf");//butonu oluştur
                BombaSayisitf.setFont(new Font("Terminal",Font.CENTER_BASELINE,24));
                BombaSayisitf.setBounds(16,17,70, 45);
                BombaSayisitf.setEnabled(false);
                BombaSayisitf.setDisabledTextColor(new Color(204,0,0));
                BombaSayisitf.setBackground(new Color(102,102,102));
                BombaSayisitf.setForeground(new Color(204,0,0)); 
                BombaSayisitf.setName("BombaSayisitf");
                BombaSayisitf.setText("");
                BombaSayisitf.setHorizontalAlignment(SwingConstants.CENTER);
                Border kaplama2=BorderFactory.createLoweredSoftBevelBorder();
                BombaSayisitf.setBorder(kaplama2);
                this.add(BombaSayisitf);
           
                GecenZamantf = new JTextField("GecenZamantf");//butonu oluşturnew 
                GecenZamantf.setFont(new Font("Terminal",Font.CENTER_BASELINE,24));
                GecenZamantf.setBounds(1190,17,70, 45);
                GecenZamantf.setEnabled(false);
                GecenZamantf.setDisabledTextColor(new Color(204,0,0));
                GecenZamantf.setBackground(new Color(102,102,102));
                GecenZamantf.setForeground(new Color(204,0,0)); 
                GecenZamantf.setHorizontalAlignment(SwingConstants.CENTER);
                GecenZamantf.setName("GecenZamantf");
                GecenZamantf.setBorder(kaplama2);
                GecenZamantf.setText("");
                 this.add(GecenZamantf);
           
           final JButton YenidenBaslatbt = new JButton("YenidenBaslatbt");//butonu oluştur
               YenidenBaslatbt.setFont(new Font("Tahoma", Font.PLAIN, 9));
                YenidenBaslatbt.setBounds(588,18,124, 45);
                YenidenBaslatbt.setBackground(Color.green);
                YenidenBaslatbt.setForeground(Color.black); 
                YenidenBaslatbt.setName("YenidenBaslatbt");
                YenidenBaslatbt.setText("Yeniden Başlat");
                YenidenBaslatbt.addActionListener(new Yenidenbaslat());
                 this.add(YenidenBaslatbt);
            final JPanel Jpanel2 = new JPanel();//paneli oluştur
               Jpanel2.setFont(new Font("Tahoma", Font.PLAIN, 9));
                Jpanel2.setBounds(10,10, 1255, 60);
                Jpanel2.setBackground(Color.lightGray);
                Jpanel2.setName("YenidenBaslatbt");
                Border kaplama=BorderFactory.createLoweredBevelBorder();
                Jpanel2.setBorder(kaplama);
                 this.add(Jpanel2);
        }
        
        
        
        
        
        
        
        Random ata=new Random();
        int Numara=0;
     for (int i =2; i < a+2; i++) {
            for (int j = 1; j < b+1; j++) {
               final JButton btn_ij = new JButton(Integer.toString(i));
               btn_ij.setFont(new Font("Tahoma", Font.PLAIN, 9));
                btn_ij.setBounds(j*40,i*40, 40, 40);
                btn_ij.setBackground(Color.green);
                btn_ij.setForeground(Color.black); 
                btn_ij.setName(Integer.toString(j+Numara-1));
                btn_ij.setText("");
                btn_ij.addActionListener(new Listener());
                 dizi.add(btn_ij);
                int deger=ata.nextInt(2);
                if (deger==1 && a==9 && b==9 && ToplamBombaSayisi>9) {
                         dizidurum.add(Numara+j-1,0);//0 dan 1 e kadar değer atar 0 boş 1 bomba 
                }
                else if (deger==1 && a==16 && b==16 && ToplamBombaSayisi>39) {
                        dizidurum.add(Numara+j-1,0);//0 dan 1 e kadar değer atar 0 boş 1 bomba 
                }
                else if (deger==1 && a==16 && b==30 && ToplamBombaSayisi>98) {
                         dizidurum.add(Numara+j-1,0);//0 dan 1 e kadar değer atar 0 boş 1 bomba 
                }
                
                else
                {
                         dizidurum.add(Numara+j-1,deger);
                         if (deger==1) {
                            ToplamBombaSayisi++;   
                        }    
                }
                this.add(btn_ij);     
            }
                Numara+=b;
     }
     BombaSayisitf.setText(String.valueOf(ToplamBombaSayisi));
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AnaEkran().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem BeginnerjCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem CustomjCheckBoxMenuItem;
    private javax.swing.JMenuItem ExitjMenuItem;
    private javax.swing.JCheckBoxMenuItem ExpertjCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem IntermediatejCheckBoxMenuItem;
    private javax.swing.JMenuItem NewjMenuItem;
    private javax.swing.JMenu OyunjMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
